### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by ragrub** [arobase-che/md-attr-parser#6]
Hi and thanks for your great work!
I have a question about the license, in the package.json it's mentioned as "GPL-3.0-or-later", however in the documentation of both md-attr-parser and remark-attr it's stated MIT.

Which one to go with?

**Comment by arobase-che** [comment]
Hi \o

Definitively MIT !
Thank you for reporting this :D

Edit: 30c365c
Will be published soon.

**Comment by arobase-che** [comment]
Since it's been published. I'm closing this issue ^^
